Absorb rhaptos.cnxmlutils
openstax/cnx-transforms pull request #21
Opened 2022-09-30 20:47 UTC by philschatz

Move the XSLT files into this repository while preserving history.

This is part of moving the code out of tiny packages and into [enki](https://github.com/openstax/enki) directly

2022-09-30 20:49 UTC, philschatz commented
Closing and reopening the PR to trigger the GitHub Actions

2022-10-03 15:10 UTC, therealmarv requested changes
There are pycache `.pyc` files included. I'm not a pycache expert (correct me if I'm wrong) but they should not be included?

2022-10-03 20:39 UTC, therealmarv requested changes
Open question: Do we need new instructions on how to create new tests?

I used method described [here in rapthos.cnxmlutils](https://github.com/openstax/rhaptos.cnxmlutils/blob/master/README.txt#L11-L16) quite often for building new test cases easily from source CNXML files.

Another (minor) change request:
* update docs/changes.rst regarding moving rhaptos.cnxmlutils and removing python 2 support.

2022-10-04 15:55 UTC, therealmarv approved these changes

2022-10-04 15:59 UTC, merged